import 'package:noam_learns_english/models/word.dart';

List<Word> defaultWords = [
  Word(english: 'boy', hebrew: 'ילד', color: WordColor.newWord),
  Word(english: 'girl', hebrew: 'ילדה', color: WordColor.newWord),
  Word(english: 'mom', hebrew: 'אמא', color: WordColor.newWord),
  Word(english: 'dog', hebrew: 'כלב', color: WordColor.newWord),
  Word(english: 'cat', hebrew: 'חתול', color: WordColor.newWord),
  Word(english: 'elephant', hebrew: 'פיל', color: WordColor.newWord),
  Word(english: 'egg', hebrew: 'ביצה', color: WordColor.newWord),
  Word(english: 'eraser', hebrew: 'מחק', color: WordColor.newWord),
  Word(english: 'school', hebrew: 'בית ספר', color: WordColor.newWord),
  Word(english: 'pencil', hebrew: 'עפרון', color: WordColor.newWord),
  Word(english: 'table', hebrew: 'שולחן', color: WordColor.newWord),
  Word(english: 'bed', hebrew: 'מיטה', color: WordColor.newWord),
  Word(english: 'black', hebrew: 'שחור', color: WordColor.newWord),
  Word(english: 'white', hebrew: 'לבן', color: WordColor.newWord),
  Word(english: 'red', hebrew: 'אדום', color: WordColor.newWord),
  Word(english: 'blue', hebrew: 'כחול', color: WordColor.newWord),
  Word(english: 'zero', hebrew: 'אפס', color: WordColor.newWord),
  Word(english: 'one', hebrew: 'אחת', color: WordColor.newWord),
  Word(english: 'two', hebrew: 'שתיים', color: WordColor.newWord),
  Word(english: 'baby', hebrew: 'תינוק', color: WordColor.newWord),
  Word(english: 'bag', hebrew: 'תיק', color: WordColor.newWord),
  Word(english: 'book', hebrew: 'ספר', color: WordColor.newWord),
  Word(english: 'box', hebrew: 'קופסה', color: WordColor.newWord),
  Word(english: 'big', hebrew: 'גדול', color: WordColor.newWord),
  Word(english: 'small', hebrew: 'קטן', color: WordColor.newWord),
  Word(english: 'play', hebrew: 'לשחק', color: WordColor.newWord),
  Word(english: 'sing', hebrew: 'לשיר', color: WordColor.newWord),
  Word(english: 'run', hebrew: 'לרוץ', color: WordColor.newWord),
  Word(english: 'rest', hebrew: 'לנוח', color: WordColor.newWord),
  Word(english: 'hen', hebrew: 'תרנגולת', color: WordColor.newWord),
  Word(english: 'rabbit', hebrew: 'ארנבת', color: WordColor.newWord),
  Word(english: 'best', hebrew: 'טוב ביותר', color: WordColor.newWord),
  Word(english: 'hand', hebrew: 'יד', color: WordColor.newWord),
  Word(english: 'horse', hebrew: 'סוס', color: WordColor.newWord),
  Word(english: 'happy', hebrew: 'שמח', color: WordColor.newWord),
  Word(english: 'good', hebrew: 'טוב', color: WordColor.newWord),
  Word(english: 'tall', hebrew: 'גבוה', color: WordColor.newWord),
  Word(english: 'fast', hebrew: 'מהיר', color: WordColor.newWord),
  Word(english: 'ball', hebrew: 'כדור', color: WordColor.newWord),
  Word(english: 'in', hebrew: 'בתוך', color: WordColor.newWord),
  Word(english: 'on', hebrew: 'על', color: WordColor.newWord),
  Word(english: 'pupil', hebrew: 'תלמיד', color: WordColor.newWord),
  Word(english: 'picture', hebrew: 'תמונה', color: WordColor.newWord),
  Word(english: 'chair', hebrew: 'כיסא', color: WordColor.newWord),
  Word(english: 'lost', hebrew: 'אבוד', color: WordColor.newWord),
  Word(english: 'ask', hebrew: 'לשאול', color: WordColor.newWord),
  Word(english: 'lamp', hebrew: 'מנורה', color: WordColor.newWord),
  Word(english: 'mat', hebrew: 'שטיח', color: WordColor.newWord),
  Word(english: 'milk', hebrew: 'חלב', color: WordColor.newWord),
  Word(english: 'floor', hebrew: 'רצפה', color: WordColor.newWord),
  Word(english: 'garden', hebrew: 'גינה', color: WordColor.newWord),
  Word(english: 'kitchen', hebrew: 'מטבח', color: WordColor.newWord),
  Word(english: 'mad', hebrew: 'כועס/משוגע', color: WordColor.newWord),
  Word(english: 'lunch', hebrew: 'ארוחת צהריים', color: WordColor.newWord),
  Word(english: 'juice', hebrew: 'מיץ', color: WordColor.newWord),
  Word(english: 'cookie', hebrew: 'עוגייה', color: WordColor.newWord),
  Word(english: 'chicken', hebrew: 'תרנגולת', color: WordColor.newWord),
  Word(english: 'car', hebrew: 'מכונית', color: WordColor.newWord),
  Word(english: 'plan', hebrew: 'תוכנית', color: WordColor.newWord),
  Word(english: 'eat', hebrew: 'לאכול', color: WordColor.newWord),
  Word(english: 'sofa', hebrew: 'ספה', color: WordColor.newWord),
  Word(english: 'sun', hebrew: 'שמש', color: WordColor.newWord),
  Word(english: 'sunny', hebrew: 'שמשי', color: WordColor.newWord),
  Word(english: 'hot', hebrew: 'חם', color: WordColor.newWord),
  Word(english: 'cold', hebrew: 'קר', color: WordColor.newWord),
  Word(english: 'living room', hebrew: 'סלון', color: WordColor.newWord),
  Word(english: 'farm', hebrew: 'חווה', color: WordColor.newWord),
  Word(english: 'cow', hebrew: 'פרה', color: WordColor.newWord),
  Word(english: 'carrot', hebrew: 'גזר', color: WordColor.newWord),
  Word(english: 'leg', hebrew: 'רגל', color: WordColor.newWord),
  Word(english: 'brown', hebrew: 'חום', color: WordColor.newWord),
  Word(english: 'they', hebrew: 'הם', color: WordColor.newWord),
  Word(english: 'now', hebrew: 'עכשיו', color: WordColor.newWord),
  Word(english: 'hungry', hebrew: 'רעב', color: WordColor.newWord),
  Word(english: 'mouse', hebrew: 'עכבר', color: WordColor.newWord),
  Word(english: 'sheep', hebrew: 'כבשה', color: WordColor.newWord),
  Word(english: 'tree', hebrew: 'עץ', color: WordColor.newWord),
  Word(english: 'friend', hebrew: 'חבר', color: WordColor.newWord),
  Word(english: 'job', hebrew: 'עבודה', color: WordColor.newWord),
  Word(english: 'soft', hebrew: 'רך', color: WordColor.newWord),
  Word(english: 'fun', hebrew: 'כיף', color: WordColor.newWord),
  Word(english: 'teacher', hebrew: 'מורה', color: WordColor.newWord),
  Word(english: 'test', hebrew: 'מבחן', color: WordColor.newWord),
  Word(english: 'pen', hebrew: 'עט', color: WordColor.newWord),
  Word(english: 'pencile case', hebrew: 'קלמר', color: WordColor.newWord),
  Word(english: 'hat', hebrew: 'כובע', color: WordColor.newWord),
  Word(english: 'add', hebrew: 'להוסיף', color: WordColor.newWord),
  Word(english: 'plus', hebrew: 'פלוס', color: WordColor.newWord),
  Word(english: 'three', hebrew: 'שלוש', color: WordColor.newWord),
  Word(english: 'four', hebrew: 'ארבע', color: WordColor.newWord),
  Word(english: 'five', hebrew: 'חמש', color: WordColor.newWord),
  Word(english: 'six', hebrew: 'שש', color: WordColor.newWord),
  Word(english: 'eleven', hebrew: 'אחד עשר', color: WordColor.newWord),
  Word(english: 'seven', hebrew: 'שבע', color: WordColor.newWord),
  Word(english: 'eight', hebrew: 'שמונה', color: WordColor.newWord),
  Word(english: 'nine', hebrew: 'תשע', color: WordColor.newWord),
  Word(english: 'ten', hebrew: 'עשר', color: WordColor.newWord),
  Word(english: 'twelve', hebrew: 'שנים עשר', color: WordColor.newWord),
  Word(english: 'apple', hebrew: 'תפוח', color: WordColor.newWord),
  Word(english: 'man', hebrew: 'איש', color: WordColor.newWord),
  Word(english: 'woman', hebrew: 'אישה', color: WordColor.newWord),
  Word(english: 'green', hebrew: 'ירוק', color: WordColor.newWord),
  Word(english: 'orange', hebrew: 'כתום', color: WordColor.newWord),
  Word(english: 'yellow', hebrew: 'צהוב', color: WordColor.newWord),
  Word(english: 'notebook', hebrew: 'מחברת', color: WordColor.newWord),
  Word(english: 'nose', hebrew: 'אף', color: WordColor.newWord),
  Word(english: 'mouth', hebrew: 'פה', color: WordColor.newWord),
  Word(english: 'computer', hebrew: 'מחשב', color: WordColor.newWord),
  Word(english: 'sister', hebrew: 'אחות', color: WordColor.newWord),
  Word(english: 'brother', hebrew: 'אח', color: WordColor.newWord),
  Word(english: 'dad', hebrew: 'אבא', color: WordColor.newWord),
  Word(english: 'desk', hebrew: 'שולחן עבודה', color: WordColor.newWord),
  Word(english: 'duck', hebrew: 'ברווז', color: WordColor.newWord),
  Word(english: 'help', hebrew: 'עזרה', color: WordColor.newWord),
  Word(english: 'sad', hebrew: 'עצוב', color: WordColor.newWord),
  Word(english: 'bad', hebrew: 'רע', color: WordColor.newWord),
  Word(english: 'grandma', hebrew: 'סבתא', color: WordColor.newWord),
  Word(english: 'grandpa', hebrew: 'סבא', color: WordColor.newWord),
  Word(english: 'gift', hebrew: 'מתנה', color: WordColor.newWord),
  Word(english: 'gray', hebrew: 'אפור', color: WordColor.newWord),
  Word(english: 'door', hebrew: 'דלת', color: WordColor.newWord),
  Word(english: 'house', hebrew: 'בית', color: WordColor.newWord),
  Word(english: 'jump', hebrew: 'לקפוץ', color: WordColor.newWord),
  Word(english: 'party', hebrew: 'מסיבה', color: WordColor.newWord),
  Word(english: 'game', hebrew: 'משחק', color: WordColor.newWord),
  Word(english: 'foot', hebrew: 'כף רגל', color: WordColor.newWord),
  Word(english: 'family', hebrew: 'משפחה', color: WordColor.newWord),
  Word(english: 'fish', hebrew: 'דג', color: WordColor.newWord),
  Word(english: 'pet', hebrew: 'חיית מחמד', color: WordColor.newWord),
  Word(english: 'birthday', hebrew: 'יום הולדת', color: WordColor.newWord),
  Word(english: 'card', hebrew: 'כרטיס', color: WordColor.newWord),
  Word(english: 'swim', hebrew: 'לשחות', color: WordColor.newWord),
  Word(english: 'you', hebrew: 'אתה', color: WordColor.newWord),
  Word(english: 'under', hebrew: 'מתחת', color: WordColor.newWord),
  Word(english: 'umbrella', hebrew: 'מטריה', color: WordColor.newWord),
  Word(english: 'glad', hebrew: 'שמח', color: WordColor.newWord),
  Word(english: 'king', hebrew: 'מלך', color: WordColor.newWord),
  Word(english: 'water', hebrew: 'מים', color: WordColor.newWord),
  Word(english: 'window', hebrew: 'חלון', color: WordColor.newWord),
  Word(english: 'queen', hebrew: 'מלכה', color: WordColor.newWord),
  Word(english: 'eyes', hebrew: 'עיניים', color: WordColor.newWord),
  Word(english: 'ears', hebrew: 'אוזניים', color: WordColor.newWord),
  Word(english: 'monkey', hebrew: 'קוף', color: WordColor.newWord),
  Word(english: 'zoo', hebrew: 'גן חיות', color: WordColor.newWord),
  Word(english: 'kid', hebrew: 'ילד', color: WordColor.newWord),
  Word(english: 'long', hebrew: 'ארוך', color: WordColor.newWord),
  Word(english: 'great', hebrew: 'נהדר', color: WordColor.newWord),
  Word(english: 'talk', hebrew: 'לדבר', color: WordColor.newWord),
  Word(english: 'cut', hebrew: 'לחתוך', color: WordColor.newWord),
  Word(english: 'van', hebrew: 'רכב גדול', color: WordColor.newWord),
  Word(english: 'magic', hebrew: 'קסם', color: WordColor.newWord),
  Word(english: 'head', hebrew: 'ראש', color: WordColor.newWord),
  Word(english: 'quiet', hebrew: 'שקט', color: WordColor.newWord),
  Word(english: 'top', hebrew: 'למעלה/עליון/מכסה', color: WordColor.newWord),
  Word(english: 'ice cream', hebrew: 'גלידה', color: WordColor.newWord),
  Word(english: 'candy', hebrew: 'סוכרייה', color: WordColor.newWord),
  Word(english: 'cake', hebrew: 'עוגה', color: WordColor.newWord),
];

List<Word> nextQuizWords = [
  Word(english: 'eraser', hebrew: 'מחק', color: WordColor.newWord),
  Word(english: 'school', hebrew: 'בית ספר', color: WordColor.newWord),
  Word(english: 'pencil', hebrew: 'עפרון', color: WordColor.newWord),
  Word(english: 'table', hebrew: 'שולחן', color: WordColor.newWord),
  Word(english: 'bed', hebrew: 'מיטה', color: WordColor.newWord),
  Word(english: 'let\'s go', hebrew: 'בוא נלך', color: WordColor.newWord),
  Word(english: 'test', hebrew: 'מבחן', color: WordColor.newWord),
  Word(english: 'teacher', hebrew: 'מורה', color: WordColor.newWord),
  Word(english: 'pen', hebrew: 'עט', color: WordColor.newWord),
  Word(english: 'pencile case', hebrew: 'קלמר', color: WordColor.newWord),
  Word(english: 'hat', hebrew: 'כובע', color: WordColor.newWord),
  Word(english: 'add', hebrew: 'להוסיף', color: WordColor.newWord),
  Word(english: 'plus', hebrew: 'פלוס', color: WordColor.newWord),
  Word(english: 'stand up', hebrew: 'קום', color: WordColor.newWord),
  Word(english: 'sit down', hebrew: 'שב', color: WordColor.newWord),
  Word(english: 'in', hebrew: 'בתוך', color: WordColor.newWord),
  Word(english: 'on', hebrew: 'על', color: WordColor.newWord),
  Word(english: 'pupil', hebrew: 'תלמיד', color: WordColor.newWord),
  Word(english: 'picture', hebrew: 'תמונה', color: WordColor.newWord),
  Word(english: 'chair', hebrew: 'כיסא', color: WordColor.newWord),
  Word(english: 'lost', hebrew: 'אבוד', color: WordColor.newWord),
  Word(english: 'ask', hebrew: 'לשאול', color: WordColor.newWord),
  Word(english: 'where\'s...?', hebrew: 'איפה...?', color: WordColor.newWord),
  Word(english: 'it\'s in', hebrew: 'זה בתוך', color: WordColor.newWord),
  Word(english: 'it\'s on', hebrew: 'זה על', color: WordColor.newWord),
  Word(english: 'play', hebrew: 'לשחק', color: WordColor.newWord),
  Word(english: 'sing', hebrew: 'לשיר', color: WordColor.newWord),
  Word(english: 'run', hebrew: 'לרוץ', color: WordColor.newWord),
  Word(english: 'rest', hebrew: 'לנוח', color: WordColor.newWord),
  Word(english: 'hen', hebrew: 'תרנגולת', color: WordColor.newWord),
  Word(english: 'rabbit', hebrew: 'ארנבת', color: WordColor.newWord),
  Word(english: 'best', hebrew: 'הכי טוב / טוב ביותר', color: WordColor.newWord),
  Word(english: 'what\'s this?', hebrew: 'מה זה?', color: WordColor.newWord),
  Word(english: 'family', hebrew: 'משפחה', color: WordColor.newWord),
  Word(english: 'fish', hebrew: 'דג', color: WordColor.newWord),
  Word(english: 'pet', hebrew: 'חיית מחמד', color: WordColor.newWord),
  Word(english: 'birthday', hebrew: 'יום הולדת', color: WordColor.newWord),
  Word(english: 'card', hebrew: 'כרטיס', color: WordColor.newWord),
  Word(english: 'swim', hebrew: 'לשחות', color: WordColor.newWord),
  Word(english: 'you', hebrew: 'אתה', color: WordColor.newWord),
  Word(english: 'there\'s a', hebrew: 'יש', color: WordColor.newWord),
  Word(english: 'happy birthday', hebrew: 'יום הולדת שמח', color: WordColor.newWord),
  Word(english: 'under', hebrew: 'מתחת', color: WordColor.newWord),
  Word(english: 'umbrella', hebrew: 'מטריה', color: WordColor.newWord),
  Word(english: 'jump', hebrew: 'לקפוץ', color: WordColor.newWord),
  Word(english: 'party', hebrew: 'מסיבה', color: WordColor.newWord),
  Word(english: 'game', hebrew: 'משחק', color: WordColor.newWord),
  Word(english: 'foot', hebrew: 'כף רגל', color: WordColor.newWord),
  Word(english: 'glad', hebrew: 'שמח', color: WordColor.newWord),
  Word(english: 'put', hebrew: 'לשים', color: WordColor.newWord),
  Word(english: 'play a game', hebrew: 'לשחק משחק', color: WordColor.newWord),
  Word(english: 'king', hebrew: 'מלך', color: WordColor.newWord),
  Word(english: 'water', hebrew: 'מים', color: WordColor.newWord),
  Word(english: 'window', hebrew: 'חלון', color: WordColor.newWord),
  Word(english: 'queen', hebrew: 'מלכה', color: WordColor.newWord),
  Word(english: 'eyes', hebrew: 'עיניים', color: WordColor.newWord),
  Word(english: 'ears', hebrew: 'אוזניים', color: WordColor.newWord),
  Word(english: 'monkey', hebrew: 'קוף', color: WordColor.newWord),
  Word(english: 'i can', hebrew: 'אני יכול', color: WordColor.newWord),
  Word(english: 'me', hebrew: 'אני', color: WordColor.newWord),
  Word(english: 'zoo', hebrew: 'גן חיות', color: WordColor.newWord),
  Word(english: 'quiet', hebrew: 'שקט', color: WordColor.newWord),
  Word(english: 'top', hebrew: 'ראש', color: WordColor.newWord),
  Word(english: 'ice cream', hebrew: 'גלידה', color: WordColor.newWord),
  Word(english: 'candy', hebrew: 'סוכרייה', color: WordColor.newWord),
  Word(english: 'cake', hebrew: 'עוגה', color: WordColor.newWord),
  Word(english: 'cut', hebrew: 'לחתוך', color: WordColor.newWord),
  Word(english: 'my', hebrew: 'שלי', color: WordColor.newWord),
  Word(english: 'van', hebrew: 'רכב גדול', color: WordColor.newWord),
  Word(english: 'magic', hebrew: 'קסם', color: WordColor.newWord),
  Word(english: 'head', hebrew: 'ראש', color: WordColor.newWord),
  Word(english: 'kid', hebrew: 'ילד', color: WordColor.newWord),
  Word(english: 'long', hebrew: 'ארוך', color: WordColor.newWord),
  Word(english: 'great', hebrew: 'נהדר', color: WordColor.newWord),
  Word(english: 'talk', hebrew: 'לדבר', color: WordColor.newWord),
  Word(english: 'hot', hebrew: 'חם', color: WordColor.newWord),
  Word(english: 'cold', hebrew: 'קר', color: WordColor.newWord),
  Word(english: 'living room', hebrew: 'סלון', color: WordColor.newWord),
  Word(english: 'farm', hebrew: 'חווה', color: WordColor.newWord),
  Word(english: 'how\'s the weather?', hebrew: 'איך מזג האוויר?', color: WordColor.newWord),
  Word(english: 'it\'s hot and sunny', hebrew: 'הוא חם ושמשי', color: WordColor.newWord),
  Word(english: 'he', hebrew: 'הוא', color: WordColor.newWord),
  Word(english: 'she', hebrew: 'היא', color: WordColor.newWord),
  Word(english: 'mouse', hebrew: 'עכבר', color: WordColor.newWord),
  Word(english: 'sheep', hebrew: 'כבשה', color: WordColor.newWord),
  Word(english: 'tree', hebrew: 'עץ', color: WordColor.newWord),
  Word(english: 'friend', hebrew: 'חבר', color: WordColor.newWord),
  Word(english: 'job', hebrew: 'עבודה', color: WordColor.newWord),
  Word(english: 'soft', hebrew: 'רך', color: WordColor.newWord),
  Word(english: 'fun', hebrew: 'כיף', color: WordColor.newWord),
  Word(english: 'it\'s near', hebrew: 'זה קרוב', color: WordColor.newWord),
  Word(english: 'cow', hebrew: 'פרה', color: WordColor.newWord),
  Word(english: 'carrot', hebrew: 'גזר', color: WordColor.newWord),
  Word(english: 'leg', hebrew: 'רגל', color: WordColor.newWord),
  Word(english: 'brown', hebrew: 'חום', color: WordColor.newWord),
  Word(english: 'they', hebrew: 'הם', color: WordColor.newWord),
  Word(english: 'now', hebrew: 'עכשיו', color: WordColor.newWord),
  Word(english: 'hungry', hebrew: 'רעב', color: WordColor.newWord),
  Word(english: 'come and see', hebrew: 'בוא ותראה', color: WordColor.newWord),
  Word(english: 'lamp', hebrew: 'מנורה', color: WordColor.newWord),
  Word(english: 'mat', hebrew: 'שטיח', color: WordColor.newWord),
  Word(english: 'milk', hebrew: 'חלב', color: WordColor.newWord),
  Word(english: 'floor', hebrew: 'רצפה', color: WordColor.newWord),
  Word(english: 'garden', hebrew: 'גינה', color: WordColor.newWord),
  Word(english: 'kitchen', hebrew: 'מטבח', color: WordColor.newWord),
  Word(english: 'mad', hebrew: 'כועס/משוגע', color: WordColor.newWord),
  Word(english: 'it\'s not', hebrew: 'זה לא', color: WordColor.newWord),
  Word(english: 'lunch', hebrew: 'ארוחת צהריים', color: WordColor.newWord),
  Word(english: 'juice', hebrew: 'מיץ', color: WordColor.newWord),
  Word(english: 'cookie', hebrew: 'עוגייה', color: WordColor.newWord),
  Word(english: 'chicken', hebrew: 'תרנגולת', color: WordColor.newWord),
  Word(english: 'car', hebrew: 'מכונית', color: WordColor.newWord),
  Word(english: 'plan', hebrew: 'תוכנית', color: WordColor.newWord),
  Word(english: 'eat', hebrew: 'לאכול', color: WordColor.newWord),
  Word(english: 'i want..., please', hebrew: 'אני רוצה..., בבקשה', color: WordColor.newWord),
  Word(english: 'cheese', hebrew: 'גבינה', color: WordColor.newWord),
  Word(english: 'bus', hebrew: 'אוטובוס', color: WordColor.newWord),
  Word(english: 'ride', hebrew: 'נסיעה', color: WordColor.newWord),
  Word(english: 'get', hebrew: 'לקבל', color: WordColor.newWord),
  Word(english: 'cost', hebrew: 'עלות', color: WordColor.newWord),
  Word(english: 'who is...?', hebrew: 'מי...?', color: WordColor.newWord),
  Word(english: 'that\'s...', hebrew: 'זה...', color: WordColor.newWord),
  Word(english: 'shop', hebrew: 'חנות', color: WordColor.newWord),
  Word(english: 'short', hebrew: 'קצר', color: WordColor.newWord),
  Word(english: 'chocolate', hebrew: 'שוקולד', color: WordColor.newWord),
  Word(english: 'orange', hebrew: 'תפוז/כתום', color: WordColor.newWord),
  Word(english: 'men', hebrew: 'גברים', color: WordColor.newWord),
  Word(english: 'us', hebrew: 'אנחנו', color: WordColor.newWord),
  Word(english: 'half', hebrew: 'חצי', color: WordColor.newWord),
  Word(english: 'who has...?', hebrew: 'למי יש...?', color: WordColor.newWord),
  Word(english: 'children', hebrew: 'ילדים', color: WordColor.newWord),
  Word(english: 'bird', hebrew: 'ציפור', color: WordColor.newWord),
  Word(english: 'snake', hebrew: 'נחש', color: WordColor.newWord),
  Word(english: 'fly', hebrew: 'לעוף', color: WordColor.newWord),
  Word(english: 'send', hebrew: 'לשלוח', color: WordColor.newWord),
  Word(english: 'from', hebrew: 'מ-', color: WordColor.newWord),
  Word(english: 'both', hebrew: 'שניהם', color: WordColor.newWord),
  Word(english: 'what\'s in the...?', hebrew: 'מה יש ב...?', color: WordColor.newWord),
  Word(english: 'Sunday', hebrew: 'ראשון', color: WordColor.newWord),
  Word(english: 'Monday', hebrew: 'שני', color: WordColor.newWord),
  Word(english: 'Tuesday', hebrew: 'שלישי', color: WordColor.newWord),
  Word(english: 'Wednesday', hebrew: 'רביעי', color: WordColor.newWord),
  Word(english: 'Thursday', hebrew: 'חמישי', color: WordColor.newWord),
  Word(english: 'Friday', hebrew: 'שישי', color: WordColor.newWord),
  Word(english: 'Saturday', hebrew: 'שבת', color: WordColor.newWord),
  Word(english: 'on...', hebrew: 'ב...', color: WordColor.newWord),
  Word(english: 'home', hebrew: 'בית', color: WordColor.newWord),
  Word(english: 'trip', hebrew: 'טיול', color: WordColor.newWord),
  Word(english: 'camp', hebrew: 'מחנה/קייטנה', color: WordColor.newWord),
  Word(english: 'summer', hebrew: 'קיץ', color: WordColor.newWord),
  Word(english: 'lake', hebrew: 'אגם', color: WordColor.newWord),
  Word(english: 'last', hebrew: 'אחרון', color: WordColor.newWord),
  Word(english: 'at home', hebrew: 'בבית', color: WordColor.newWord),
];